name: Content Changes Table Comment

# **What it does**: When a PR is opened in docs-internal or docs, it adds the staging preview and live article links in a Content Directory Changes table in a comment
# **Why we have it**: To help Docs Content team members and contributors automatically have their staging/live article links added to the table
# **Who does it impact**: docs-internal/docs maintainers and contributors

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  PR-Preview-Links:
    name: Add staging/live links to PR
    runs-on: ubuntu-latest
    outputs:
      filterContentDir: ${{ steps.filter.outputs.filterContentDir }}
    steps:
      - name: Get files changed
        uses: dorny/paths-filter@eb75a1edc117d3756a18ef89958ee59f9500ba58
        id: filter
        with:
          # Base branch used to get changed files
          base: ${{ github.event.pull_request.base.ref }}

          # Enables setting an output in the format in `${FILTER_NAME}_files
          # with the names of the matching files formatted as JSON array
          list-files: json

          # Returns list of changed files matching each filter
          filters: |
            filterContentDir:
              - 'content/**/*'

  filterContentDir:
    needs: PR-Preview-Links
    if: ${{ needs.PR-Preview-Links.outputs.filterContentDir == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: check out repo content
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97

      - name: Setup Node
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install temporary dependencies
        run: |
          npm install --no-save github-slugger
          npm install --no-save --include=optional esm

      - name: Get changes table
        uses: actions/github-script@2b34a689ec86a68d8ab9478298f91d5401337b7d
        id: changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            // Workaround to allow us to load ESM files with `require(...)`
            const esm = require('esm')
            require = esm({})

            const { default: createStagingAppName } = require('./script/deployment/create-staging-app-name')

            const stagingPrefix = createStagingAppName({
              repo: context.payload.repository.name,
              pullNumber: context.payload.number,
              branch: context.payload.pull_request.head.ref,
            })

            const response = await github.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: context.payload.pull_request.base.sha,
              head: context.payload.pull_request.head.sha
            })

            const files = response.data.files

            let markdownTable = '| **Source** | **Staging** | **Production** | **What Changed** |\n|:----------- |:----------- |:----------- |:----------- |\n'

            const pathPrefix = 'content/'
            const articleFiles = files.filter(({ filename }) => filename.startsWith(pathPrefix) && !filename.endsWith('/index.md'))
            for (const file of articleFiles) {
              const sourceUrl = file.blob_url
              const fileName = file.filename.slice(pathPrefix.length)
              const fileUrl = fileName.slice(0, fileName.lastIndexOf('.'))
              const stagingLink = `https://${stagingPrefix}.herokuapp.com/${fileUrl}`
              const productionLink = `https://docs.github.com/${fileUrl}`
              let markdownLine = ''

              if (file.status === 'modified') {
                markdownLine = `| [content/${fileName}](${sourceUrl}) | [Modified](${stagingLink}) | [Original](${productionLink}) | |\n`
              } else if (file.status === 'added') {
                markdownLine = `| New file: [content/${fileName}](${sourceUrl}) | [Modified](${stagingLink}) | | |\n`
              }
              markdownTable += markdownLine
            }

            core.setOutput('changesTable', markdownTable)

      - name: Find content directory changes comment
        uses: peter-evans/find-comment@d2dae40ed151c634e4189471272b57e76ec19ba8
        id: findComment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- MODIFIED_CONTENT_LINKING_COMMENT -->'

      - name: Update comment
        uses: peter-evans/create-or-update-comment@5221bf4aa615e5c6e95bb142f9673a9c791be2cd
        with:
          comment-id: ${{ steps.findComment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            <!-- MODIFIED_CONTENT_LINKING_COMMENT -->
            ## Automatically generated comment ℹ️
            **This comment is automatically generated and will be overwritten every time changes are committed to this branch.**

            The table contains an overview of files in the `content` directory that have been changed in this pull request. It's provided to make it easy to review your changes on the staging site. Please note that changes to the `data` directory will not show up in this table.

            ---

            ### Content directory changes
            _You may find it useful to copy this table into the pull request summary. There you can edit it to share links to important articles or changes and to give a high-level overview of how the changes in your pull request support the overall goals of the pull request._
            ${{ steps.changes.outputs.changesTable }}
          edit-mode: replace
2021-12-15T10:06:40.6944238Z Found online and idle hosted runner in the current repository's organization account that matches the required labels: 'ubuntu-latest'
2021-12-15T10:06:40.7630487Z Waiting for a Hosted runner in the 'organization' to pick this job...
2021-12-15T10:06:42.0854042Z Job is waiting for a hosted runner to come online.
2021-12-15T10:06:44.9180977Z Job is about to start running on the hosted runner: Hosted Agent (hosted)
2021-12-15T10:06:53.3162641Z Current runner version: '2.285.1'
2021-12-15T10:06:53.3190213Z ##[group]Operating System
2021-12-15T10:06:53.3191168Z Ubuntu
2021-12-15T10:06:53.3191582Z 20.04.3
2021-12-15T10:06:53.3192039Z LTS
2021-12-15T10:06:53.3192524Z ##[endgroup]
2021-12-15T10:06:53.3193082Z ##[group]Virtual Environment
2021-12-15T10:06:53.3193720Z Environment: ubuntu-20.04
2021-12-15T10:06:53.3194235Z Version: 20211209.3
2021-12-15T10:06:53.3195230Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20211209.3/images/linux/Ubuntu2004-README.md
2021-12-15T10:06:53.3196579Z Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20211209.3
2021-12-15T10:06:53.3197421Z ##[endgroup]
2021-12-15T10:06:53.3198043Z ##[group]Virtual Environment Provisioner
2021-12-15T10:06:53.3198626Z 1.0.0.0-main-20211208-1
2021-12-15T10:06:53.3199146Z ##[endgroup]
2021-12-15T10:06:53.3201282Z ##[group]GITHUB_TOKEN Permissions
2021-12-15T10:06:53.3202603Z Actions: write
2021-12-15T10:06:53.3203216Z Checks: write
2021-12-15T10:06:53.3203806Z Contents: write
2021-12-15T10:06:53.3204326Z Deployments: write
2021-12-15T10:06:53.3204915Z Discussions: write
2021-12-15T10:06:53.3205396Z Issues: write
2021-12-15T10:06:53.3205905Z Metadata: read
2021-12-15T10:06:53.3206382Z Packages: write
2021-12-15T10:06:53.3206906Z Pages: write
2021-12-15T10:06:53.3207423Z PullRequests: write
2021-12-15T10:06:53.3208058Z RepositoryProjects: write
2021-12-15T10:06:53.3208701Z SecurityEvents: write
2021-12-15T10:06:53.3209244Z Statuses: write
2021-12-15T10:06:53.3209865Z ##[endgroup]
2021-12-15T10:06:53.3212662Z Secret source: Actions
2021-12-15T10:06:53.3213602Z Prepare workflow directory
2021-12-15T10:06:53.3798432Z Prepare all required actions
2021-12-15T10:06:53.3808724Z Getting action download info
2021-12-15T10:06:53.6678025Z Download action repository 'dorny/paths-filter@eb75a1edc117d3756a18ef89958ee59f9500ba58' (SHA:eb75a1edc117d3756a18ef89958ee59f9500ba58)
2021-12-15T10:06:56.5776920Z ##[group]Run dorny/paths-filter@eb75a1edc117d3756a18ef89958ee59f9500ba58
2021-12-15T10:06:56.5777851Z with:
2021-12-15T10:06:56.5778240Z   base: main
2021-12-15T10:06:56.5778670Z   list-files: json
2021-12-15T10:06:56.5779248Z   filters: filterContentDir:
  - 'content/**/*'

2021-12-15T10:06:56.5780270Z   token: ***
2021-12-15T10:06:56.5780772Z   initial-fetch-depth: 10
2021-12-15T10:06:56.5781267Z ##[endgroup]
2021-12-15T10:06:56.8229459Z ##[group]Fetching list of changed files for PR#35 from Github API
2021-12-15T10:06:56.8231420Z Number of changed_files is 2
2021-12-15T10:06:56.8336788Z Invoking listFiles(pull_number: 35, page: 1, per_page: 100)
2021-12-15T10:06:57.1773946Z [modified] .github/workflows/crowdin-cleanup.yml
2021-12-15T10:06:57.1776758Z [modified] .github/workflows/openapi-decorate.yml
2021-12-15T10:06:57.1779534Z ##[endgroup]
2021-12-15T10:06:57.1786324Z Results:
2021-12-15T10:06:57.1788450Z ##[group]Filter filterContentDir = false
2021-12-15T10:06:57.1789240Z Matching files: none
2021-12-15T10:06:57.1822623Z ##[endgroup]
2021-12-15T10:06:57.1897911Z Evaluate and set job outputs
2021-12-15T10:06:57.1916608Z Set output 'filterContentDir'
2021-12-15T10:06:57.1919187Z Cleaning up orphan processes
